### PR TITLE
radio_buttons custom label support

### PR DESCRIPTION
**Pull request by mwanji**
This works in my application, but I haven't been able to run the test suite. Please test and let me know if there's a problem.

### CODE REVIEW

**Comment by sethvargo** [comment]
The tests passed. Any particular reason you can't run the suite?

**Comment by mwanji** [comment]
Cool, thanks for pulling in the changes.

"Any particular reason you can't run the suite?"

I'm probably making a newbie mistake somewhere. After installing the application and Bundler in a new RVM gemset, I keep on getting "bootstrap_forms/spec/dummy/config/application.rb : 5: uninitialized constant Bundler (NameError)" when running rake spec.

**Comment by sethvargo** [comment]
hmm... sounds like bundler isn't being loaded up with the rake tasks....

**Comment by mwanji** [comment]
I was able to get it to run by adding require 'bundler' to application.rb.

However, it also works fine without the call to Bundler.require on line 4. Are you sure it's necessary? This is what's generated in full-blown Rails apps:

```
if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  # Bundler.require(:default, :assets, Rails.env)
end
```

**Comment by sethvargo** [comment]
I'm pretty sure that's the code the rspec autogenerates...

**Comment by mwanji** [comment]
I ran into the uninitialized constant problem again while working on a new patch and resolved it again by removing Bundler.require from application.rb.

I'm running on ruby 1.9.3-p125 on Ubuntu. Maybe different ruby versions or different platforms behave differently?

**Comment by sethvargo** [comment]
Are you running `bundle exec COMMAND` or just `COMMAND`?

**Comment by mwanji** [comment]
I was just running COMMAND, but bundle exec fixes it. Thanks! As I had initially suspected, a newbie mistake.

**Pull request merged**
