### PR TITLE
Handled the case where an object has no method validators_on

### PR DESCRIPTION
**Pull request by nerakdon**
By asking whether the object responds to `validators_on`, this fork fixes the case where an object has no such method, as is the case with MetaSearch forms.

### CODE REVIEW

**Comment by sethvargo** [comment]
Could you please add a spec for this? I just don't want to break it in later releases.

**Comment by nerakdon** [comment]
I'm not entirely sure what you mean, sorry -- I'm kind of new to this.  Do you want me to add something to the gemspec file?

**Comment by sethvargo** [comment]
Sorry. A "spec" is a test (because I use rspec)

**Comment by nerakdon** [comment]
Ok -- it took me a while, but here it is.  My research indicated it was not best practices to test directly since required_class is a private method.  Therefore, I tested a method that calls it, bootstrap_text_field_tag.  Since it raised an error message before, I made the test simply check whether the text field html returned properly.

It was a good learning experience.

**Comment by sethvargo** [comment]
Hmm, I'm getting a failure when running your test:

``` ruby
Failures:

  1) BootstrapForms::Helpers::FormTagHelper#bootstrap_text_field_tag with no method "validators_on" returns an empty string with no errors
     Failure/Error: @template.bootstrap_text_field_tag(@builder.object[:name]).should == '<div class="control-group"><label class="control-label"></label><div class="controls"><input id="" type="text" value="error" /></div></div>'
       expected: "<div class=\"control-group\"><label class=\"control-label\"></label><div class=\"controls\"><input id=\"\" type=\"text\" value=\"error\" /></div></div>"
            got: "<div class=\"control-group\"><label class=\"control-label\"></label><div class=\"controls\"><input id=\"\" type=\"text\" value=\"{:error=&gt;nil}\" /></div></div>" (using ==)
     # ./spec/lib/bootstrap_forms/form_builder_spec.rb:110:in `block (4 levels) in <top (required)>
```

**Comment by nerakdon** [comment]
Alrighty, that should do the trick.

**Pull request closed without merging**
