### PR TITLE
Ability to force required attribute

### PR DESCRIPTION
**Pull request by sigmike**
I had to make a field not optional while still having a presence validator and could not remove the "required" attribute. This patch adds a "required" option.

### CODE REVIEW

**Comment by sethvargo** [comment]
This build is failing...

**Comment by sethvargo** [comment]
@piglop can you look into the build failures?

**Comment by sigmike** [comment]
I don't have much time for that now but I'll look into that as soon as I can.

**Comment by sigmike** [comment]
Actually I don't need this anymore. My problem was fixed with #61. I didn't know because it was not published on rubygems and I guessed the gem was up to date.
Do you want this feature anyway?

**Comment by sethvargo** [comment]
I can cut a new version if that would help.

**Pull request closed without merging**
