### PR TITLE
Initial Support for Bootstrap 3

### PR DESCRIPTION
**Pull request by jasontorres**
Here's a PR for initial bootstrap 3 support. This covers most of the input controls.

However, I just noticed last night, prepend and append, prepend/append w/ buttons too changed as well so we need to fix that as well. I'll see what I can do about them.

### CODE REVIEW

**Comment by sethvargo** [comment]
@jasontorres, this would be a breaking change, right? It would no longer be BS 2.0 compatible. This isn't a problem, I'm just trying to best understand the situation and changeset.

**Comment by jasontorres** [comment]
@sethvargo yes it is a breaking change and won't be 2.0 compatible.

**Comment by sethvargo** [comment]
@wingrunr21 can you elaborate on what "this" you're referring to please?

**Comment by wingrunr21** [comment]
My comment was a line comment. The class that's supposed to be set on labels in bootstrap 3 is still control-label, not form-label as was changed in the diff.

**Comment by sethvargo** [comment]
@wingrunr21 strange. Thanks!

@jasontorres can you take a look at @wingrunr21's comment?

**Comment by sethvargo** [comment]
I'm going to close this due to inactivity, but please reopen if you have more time to work on this issue.

**Pull request closed without merging**
