### PR TITLE
Create bootstrap_fields_for

### PR DESCRIPTION
**Pull request by mwanji**
This method returns a bootstrap_forms form builder for fields of an associated entity.

### CODE REVIEW

**Comment by mwanji** [comment]
There are no tests for this, as I couldn't find any tests for bootstrap_form_for and the implementation simply instantiates a Bootstrap form builder, which is already well-tested. Let me know if I should create any tests for this method.

**Comment by sethvargo** [comment]
I agree... there's not really much to "test"...

**Comment by jsmestad** [comment]
This doesn't seem to get loaded in the current `master` on GH. Am I missing something from the example above? I am getting an `undefined method` error.

**Comment by sethvargo** [comment]
@jsmestad can you open up a new issue with code samples? This code has moved into `helpers/form_helper`, and the code has changed significantly in the past 9 months.

Opening a new issue will help my prioritize it and help others search.

**Pull request merged**
